'use client'
import type { Metadata } from 'next'
import { mainnet, polygon, optimism, arbitrum,sepolia } from "wagmi/chains";
import { Inter } from 'next/font/google'
import './globals.css'
import { WagmiConfig, createConfig} from "wagmi";
import { ConnectKitProvider, getDefaultConfig } from "connectkit";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const chains = [mainnet, polygon, optimism, arbitrum, sepolia];
const config = createConfig(
  getDefaultConfig({
    // Required API Keys
    alchemyId: process.env.API_KEY,
    walletConnectProjectId: process.env.PROJECT_ID,
    // Required
    chains: chains,
    appName: "GHODiversitech",
    // Optional
    appDescription: "Your App Description",
    appUrl: "https://family.co", // your app's url
    appIcon: "https://family.co/logo.png", // your app's icon, no bigger than 1024x1024px (max. 1MB)
  }),
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
    <WagmiConfig config={config}>
      <ConnectKitProvider>
      <body className={inter.className}>{children}</body>
      
      </ConnectKitProvider>
    </WagmiConfig>
    </html>
  )
}
